https://github.com/lovedlim/BigDataCertificationCourses  
https://www.kaggle.com/datasets/agileteam/bigdatacertificationkr    
https://velog.io/@seojeongbin/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EA%B8%B0%EC%82%AC-%EC%8B%A4%EA%B8%B0-%EC%A0%95%EB%A6%AC

# 두 그룹의 평균 비교 (t-test, f-test)  
https://www.kaggle.com/code/agileteam/t3-ttest-anova-py/

문제: 두 교육 방법의 효과 비교  
연구자는 두 가지 다른 교육 방법이 학생들의 성적에 미치는 영향을 비교하고자 합니다. 연구자는 무작위로 선발된 20명의 학생들을 두 그룹으로 나누어 한 그룹에는 교육 방법 A를, 다른 그룹에는 교육 방법 B를 적용합니다. 교육이 끝난 후, 두 그룹의 성적을 비교하기 위해 독립 표본 t-검정과 ANOVA F-검정을 실시하려고 합니다.  
  
다음은 두 그룹의 성적입니다: 다음의 두 가지 검정을 사용하여 두 교육 방법 간의 성적 차이가 통계적으로 유의한지를 검증하세요  

독립 표본 t-검정을 실시하여 t 통계량을 구하세요.
독립 표본 t-검정을 실시하여 p-값을 구하세요.
ANOVA F-검정을 실시하여 F 통계량을 구하세요.
ANOVA F-검정을 실시하여 p-값을 구하세요.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'A':[77, 75, 82, 80, 81, 83, 84, 76, 75, 87],
    'B':[80, 74, 77, 79, 71, 74, 78, 69, 70, 72],
})

In [ ]:
from scipy import stats

print(stats.ttest_ind(df['A'], df['B']))

## TtestResult(statistic=np.float64(3.1068522301122954), pvalue=np.float64(0.006087373605949963), df=np.float64(18.0))
## t 통계량 : 3.1068522301122954
## p-value : 0.006087373605949963

TtestResult(statistic=np.float64(3.1068522301122954), pvalue=np.float64(0.006087373605949963), df=np.float64(18.0))

In [ ]:
stats.f_oneway(df['A'], df['B'])

## F_onewayResult(statistic=np.float64(9.652530779753763), pvalue=np.float64(0.006087373605949924))
## t 통계량 : 9.652530779753763
## p-value : 0.006087373605949924

F_onewayResult(statistic=np.float64(9.652530779753763), pvalue=np.float64(0.006087373605949924))

# 적합도 검정  
https://www.kaggle.com/code/agileteam/t3-chisquare-py

카이제곱 적합도 검정  
  
1. One Sample Chi-squared test - 적합도 검정  
 - 귀무가설(H0) : 주어진 한 변수의 분포가 기대와 동일할 것이다.  
 - 대립가설(Ha) : 주어진 한 변수의 분포가 기대와 동일하지 않을 것이다.   
 - 함수 : scipy.stats.chisquare(f_obs, exp_value)
2. Two Sample Chi-squared test - 동질성 검정
 - 귀무가설(H0) : 두 변수의 분포가 동일할 것이다.  
 - 대립가설(Ha) : 두 변수의 분포가 동일하지 않을 것이다.  
 - 함수 : scipy.stats.chisquare(f_obs, f_exp)
3. Two Sample Chi-squared test - 독립성 검정  
 - 귀무가설(H0) : 두 변수는 서로 독립이다. (관련이 없을 것이다.)  
 - 대립가설(Ha) : 두 변수는 서로 독립적이지 않다. (관련이 있을 것이다.)
 - 함수 : chi2_contingency()

<문제>  
고등학교에서는 졸업생들이 선택하는 대학 전공 분야의 선호도가 시간이 지남에 따라 변하지 않는다고 가정합니다. 학교 측은 최근 졸업생들의 전공 선택이 과거와 같은 패턴을 따르는지 알아보기 위해 적합도 검정을 실시하기로 결정했습니다.  
  
과거 자료에 따르면 졸업생들이 선택하는 전공의 분포는 다음과 같습니다:  
인문학: 20% 사회과학: 30% 자연과학: 25% 공학: 15% 기타: 10%  
  
올해 졸업한 학생 200명의 전공 선택 분포는 다음과 같았습니다:  
인문학: 30명 사회과학: 60명 자연과학: 50명 공학: 40명 기타: 20명  
  
이 데이터를 바탕으로, 졸업생들의 전공 선택 패턴이 과거와 유사한지를 알아보기 위해 카이제곱 적합도 검정을 실시해야 합니다. 유의 수준은 0.05로 설정합니다.  
  
1. 검정 통계량?  
2. p-value?  
3. 유의수준 하 귀무가설 기각 또는 채택?

In [ ]:
from scipy.stats import chisquare

In [ ]:
## 관측된 빈도
observed_previous = [30, 60, 50, 40, 20]

## 과거 자료에 따라 기대되는 빈도 (총원 200명)
expected_frequencies = [200 * 0.20, 200 * 0.30, 200 * 0.25, 200 * 0.15, 200 * 0.10]

## Chisquare
chisquare(f_obs = observed_previous, f_exp = expected_frequencies)

## F_onewayResult(statistic=np.float64(9.652530779753763), pvalue=np.float64(0.006087373605949924))
## 검정 통계량 : 9.652530779753763
## p-value : 0.006087373605949924
## 유의수즌 0.05에 따른 귀무가설 채택 여부 : p-value가 0.05 이하이므로 귀무가설이 기각되어 대립가설이 채택된다. 곧, 두 변수의 분포가 동일하지 않을 것이다.

Power_divergenceResult(statistic=np.float64(5.833333333333334), pvalue=np.float64(0.21194558437271782))

# 지지도, 신뢰도, 향상도  
https://www.kaggle.com/code/agileteam/t3-scl-py

<문제>
1. '빼빼로'와 '딴짓초코'가 함께 팔린 거래의 지지도를 계산하세요.  
2. '빼빼로'가 팔린 거래 중에서 '빼빼로'와 '오징어칩'이 함께 팔린 거래의 신뢰도를 계산하세요.  
3. '빼빼로'와 '양조위빵'의 향상도를 계산하세요.  
  

- 지지도(A, B): A와 B가 함께 팔린 거래 횟수 / 전체 거래 횟수  
- 신뢰도(A-> B): A와 B가 함께 팔린 거래 횟수 / A가 팔린 거래 횟수  
- 향상도(A, B): 신뢰도(A-> B) / 지지도(B)

In [ ]:
import pandas as pd

## Data
df = pd.DataFrame({
  'Transaction' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  , '빼빼로'    : [1, 0, 1, 1, 0, 1, 1, 0, 1, 1]
  , '딴짓초코'  : [0, 1, 1, 0, 1, 0, 1, 1, 0, 0]
  , '오징어칩'  : [0, 1, 1, 0, 0, 1, 0, 1, 1, 1]
  , '초코파이'  : [1, 1, 0, 0, 1, 0, 1, 1, 0, 0]
})
df

   Transaction  빼빼로  딴짓초코  오징어칩  초코파이
0            1    1     0     0     1
1            2    0     1     1     1
2            3    1     1     1     0
3            4    1     0     0     0
4            5    0     1     0     1
5            6    1     0     1     0
6            7    1     1     0     1
7            8    0     1     1     1
8            9    1     0     1     0
9           10    1     0     1     0

In [ ]:
## 각 문제 계산을 위한 변수
total = df.shape[0]
pepero = df['빼빼로'].sum()

print(total)
print(pepero)

10
7

In [ ]:
## 문제 01 : 빼빼로와 딴짓초코가 함께 팔린 거래의 지지도
pepero_and_choco = len(df[(df['빼빼로'] == 1 & (df['딴짓초코'] == 1))])
print(pepero_and_choco / total)

0.2

In [ ]:
## 문제 02 : 빼빼로가 팔린 거래 중 빼빼로와 오징어칩이 함께 팔린 거래의 신뢰도
pepero_and_squid = len(df[(df['빼빼로'] == 1) & (df['오징어칩'] == 1)])
print(pepero_and_squid/pepero)

0.5714285714285714

In [ ]:
## 문제 03 : 빼빼로와 양조위빵의 향상도
pepero_and_bread = len(df[(df['빼빼로'] == 1) & (df['초코파이'] == 1)])
bread = df['초코파이'].sum()
print((pepero_and_bread / pepero) / (pepero_and_bread / total))

1.4285714285714284

# 포아송분포
https://www.kaggle.com/code/agileteam/t3-pmf-py

문제: 한 서점에서는 평균적으로 하루에 3명의 고객이 특정 잡지를 구매합니다. 이 데이터는 포아송 분포를 따른다고 가정할 때, 다음 질문에 대한 답을 구하세요.  
  
하루에 정확히 5명의 고객이 잡지를 구매할 확률은 얼마입니까? (%로 값을 정수로 입력하시오)  
하루에 적어도 2명의 고객이 잡지를 구매할 확률은 얼마입니까? (%로 값을 정수로 입력하시오)

포아송 분포의 확률 질량 함수(PMF)

![포아송 분포.png]()

λ는 단위 시간(또는 단위 공간)당 평균 발생 횟수이고, k는 특정 시간(또는 공간) 동안의 이벤트 발생 횟수입니다.

In [ ]:
from scipy.stats import poisson

## 평균 사건 발생 횟수 (하루에 잡지를 구배하는 고객의 수)
lambda_ = 3

## 하루에 5명의 고객이 잡지를 구매할 확률
print(poisson.pmf(5, lambda_))

## 하루에 적어도 2명의 고객이 잡지를 구매할 확률
print(1 - poisson.cdf(1, lambda_))

0.10081881344492458
0.8008517265285442

# 성별과 시험합격은 독립적인가를 검정하시오!
https://www.kaggle.com/code/agileteam/t3-chi2-contingency-py

1. 검정 통계량?
2. p-value?
3. 귀무가설 기준 (기각/채택)?
4. 남자의 합격 기대 빈도?

![독립성.png]()

In [ ]:
import pandas as pd
from scipy import stats

## 데이터프레임 생성
df = pd.DataFrame({'남자' : [100, 200]
                   , '여자' : [130, 170]}
                   , index = ['합격', '불합격'])

## 데이터프레임 출력
print(df)

## Chisquare 검정 수행
statistic, pvalue, dof, expected = stats.chi2_contingency(df)

## 결과 출력
print(f'검정통계량 : {statistic}')
print(f'p-value : {pvalue}')
print(f'남자의 합격 기대 빈도 : {expected[0][0]}')

      남자   여자
합격   100  130
불합격  200  170
검정통계량 : 5.929494712103407
p-value : 0.01488951060599475
남자의 합격 기대 빈도 : 115.0

기대 빈도(expected frequency)는 카이제곱 검정(Chi-squared test)에서 매우 중요한 개념입니다. 이는 귀무 가설 하에서 관찰될 것으로 예상되는 빈도입니다. 귀무 가설은 일반적으로 두 변수가 서로 독립적이라고 주장합니다. 이 경우, 성별과 시험 합격 여부가 독립적이라는 것이 귀무 가설입니다.

예를 들어, 남자의 합격 기대빈도를 계산하려면 다음과 같이 계산합니다:

남자의 총합 (100 + 200)과 합격자의 총합 (100 + 130)을 구합니다.
이를 전체 합계(600)로 나눕니다.
이렇게 계산된 기대 빈도는, 두 변수가 완전히 독립적일 때 예상되는 빈도를 나타냅니다. 이 기대 빈도와 실제 관찰된 빈도 간의 차이를 분석하여, 두 변수 간의 관련성 여부를 판단합니다.

큰 차이: 실제 빈도와 기대 빈도 사이에 큰 차이가 있다면, 이는 두 변수 사이에 어떤 관계가 있을 가능성이 높다는 것을 의미합니다. 이 경우, 귀무 가설을 기각하고 대립 가설을 받아들일 수 있습니다.
작은 차이: 차이가 작거나 없다면, 두 변수 사이에 유의미한 관계가 없다고 볼 수 있으며, 귀무 가설을 기각할 충분한 근거가 없습니다.
p-value와 함께 기대 빈도는 카이제곱 검정의 핵심 결과 중 하나로, 두 변수 간의 독립성을 평가하는 데 사용됩니다.

In [ ]:
expected

array([[115., 115.],
       [185., 185.]])

# 베르누이 분포와 이항분포
https://www.kaggle.com/code/agileteam/t3-probability-py

<문제>
1. [베르누이 분포] 다음 데이터는 100번의 시도에서 각각 성공(1) 또는 실패(0)를 나타냅니다. 이 데이터를 바탕으로 각 시도의 성공 확률을 계산하시오.
2. [이항분포] 1번 문제에서 계산한 성공 확률을 사용하여, 100번의 시도 중 정확히 60번 성공할 확률을 계산하시오.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
from scipy.stats import binom

df = pd.read_csv("/content/drive/MyDrive/data_BDC/t3_success.csv")
df

    Success
0         1
1         0
2         0
3         1
4         1
..      ...
95        1
96        1
97        1
98        0
99        1

[100 rows x 1 columns]

In [ ]:
## 베르누이 분포 : 각 시도의 성공 확률 계산
total_attempts = len(df)
number_of_success = df['Success'].sum()
success_probability = number_of_success / total_attempts
print(success_probability)

0.62

In [ ]:
## 이항 분포 : 100번의 시도 중 정확히 N번 성공할 확률 계산
n = 100 ## 시도 횟수
k = 60 ## 성공 횟수
probability_of_60_success = binom.pmf(k, n, success_probability)
print(probability_of_60_success)

0.07464985555860272

binom.pmf(k, n, p) 함수는 이항 분포의 확률 질량 함수(Probability Mass Function, PMF)를 계산하는 데 사용됩니다. 이 함수는 이산 확률 분포인 이항 분포에서 특정한 성공 횟수 k가 나타날 확률을 계산합니다. 함수의 각 매개변수는 다음과 같은 의미를 가집니다:

- k : 관측하고자 하는 성공 횟수입니다.
- n : 전체 시도 횟수입니다.
- p : 각 시도에서 성공할 확률입니다.

# 점 추정과 구간 추정
https://www.kaggle.com/code/agileteam/t3-confidence-interval-py

데이터셋은 어떤 도시의 일일 평균 온도 입니다.

- 점추정: 데이터셋을 기반으로 이 도시의 평균 연간 온도를 점추정하세요. (반올림하여 소수 둘째자리까지)  
- 구간추정: 95% 신뢰수준에서 이 도시의 평균 연간 온도에 대한 신뢰구간을 구하세요. (반올림하여 소수 둘째자리까지)

In [ ]:
import pandas as pd

temperature_data = pd.read_csv("/content/drive/MyDrive/data_BDC/daily_temperatures.csv")
temperature_data

     Daily Average Temperature
0                    28.820262
1                    22.000786
2                    24.893690
3                    31.204466
4                    29.337790
..                         ...
360                  23.492286
361                  20.018854
362                  24.659242
363                  21.699825
364                  19.921589

[365 rows x 1 columns]

In [ ]:
## 점추정 : 샘플 평균 계산
sample_mean = temperature_data['Daily Average Temperature'].mean()
sample_mean

np.float64(19.937577543978538)

In [ ]:
from scipy import stats

## 구간추정 : 샘플 표준 편차 및 신뢰구간 계산
confidence_level = 0.95 ## 95% 신뢰수준
sample_std = temperature_data['Daily Average Temperature'].std()
n_samples = len(temperature_data) ## 총 샘플 수 n (자유도는 n-1)

confidence_interval = stats.t.interval(confidence_level, df = n_samples-1, loc=sample_mean, scale=sample_std/(n_samples**0.5))

In [ ]:
sample_mean, confidence_interval

(np.float64(19.937577543978538),
 (np.float64(19.427887094620406), np.float64(20.44726799333667)))

# 로지스틱 회귀모형
https://www.kaggle.com/code/agileteam/t3-2-example-py/

Pclass, Gender, sibsp, parch를 독립변수로 사용하여 로지스틱 회귀모형을 실시하였을 때, parch변수의 계수값은? 단, Pclass는 범주형 변수이다

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/data_BDC/Titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
from statsmodels.formula.api import logit

formula = "Survived ~C(Pclass) + Gender + SibSp + Parch"
model = logit(formula, data = df).fit()
model.params

Optimization terminated successfully.
         Current function value: 0.459565
         Iterations 6

Intercept         2.491729
C(Pclass)[T.2]   -0.848152
C(Pclass)[T.3]   -1.866905
Gender[T.male]   -2.760281
SibSp            -0.232553
Parch            -0.049847
dtype: float64